ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

  ALTER TABLE ot.keys ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

  CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ABC/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

  ALTER SESSION SET CONTAINER = <your PDB>;

  CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ABC/ABCPDB1/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;  