apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-oracle
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.oracle.OracleConnector
  tasksMax: 1
  config:
    tasks.max: 1
    connector.class: io.debezium.connector.oracle.OracleConnector
    database.server.name: <your server>
    database.hostname: <your server>
    database.port: 1521
    database.user: c##dbzuser
    database.password: dbz
    database.dbname: <your SID>
    database.pdb.name: <your pdb>
    database.history.kafka.bootstrap.servers: <your bootstrap servers>:9092
    database.history.kafka.topic: oracle19-history
    table.include.list: ot.keys
    message.key.columns: ot.keys:id
    transaction.topic: keys